### ISSUE TITLE
Какой основной будет шрифт для веб клиента?

### ISSUE THREAD

**Issue by Abragadabra** [lyambda/web_app#1]
Я просто знаю много хороших шрифтов, и не знаю какой использовать. Мне бы узнать ваше мнение @vsecoder @Ku6iKRu6Ika

**Comment by vsecoder** [comment]
JetBrainsMono

**Comment by Abragadabra** [comment]
Хорошо, я уже думал этот issue будет закрыт без единого коммента :)
